/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/jwt/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Jwt.Login */
        post: operations["auth_jwt_login_auth_jwt_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/jwt/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Jwt.Logout */
        post: operations["auth_jwt_logout_auth_jwt_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/jwt/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Jwt */
        post: operations["refresh_jwt_auth_jwt_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register:Register */
        post: operations["register_register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset:Forgot Password */
        post: operations["reset_forgot_password_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset:Reset Password */
        post: operations["reset_reset_password_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/request-verify-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify:Request-Token */
        post: operations["verify_request_token_auth_request_verify_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify:Verify */
        post: operations["verify_verify_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users:Current User */
        get: operations["users_current_user_accounts_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Users:Patch Current User */
        patch: operations["users_patch_current_user_accounts_me_patch"];
        trace?: never;
    };
    "/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users:User */
        get: operations["users_user_accounts__id__get"];
        put?: never;
        post?: never;
        /** Users:Delete User */
        delete: operations["users_delete_user_accounts__id__delete"];
        options?: never;
        head?: never;
        /** Users:Patch User */
        patch: operations["users_patch_user_accounts__id__patch"];
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Messages Stats */
        get: operations["get_messages_stats_messages_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show Message */
        get: operations["show_message_messages__id__get"];
        /** Update Message */
        put: operations["update_message_messages__id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients */
        get: operations["list_clients_clients_get"];
        put?: never;
        /** Create Client */
        post: operations["create_client_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{id}/verify-phone-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Verify Phone Code */
        put: operations["verify_phone_code_clients__id__verify_phone_code_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{id}/verify-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Verify Password */
        put: operations["verify_password_clients__id__verify_password_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client */
        get: operations["get_client_clients__id__get"];
        /** Update Client */
        put: operations["update_client_clients__id__put"];
        post?: never;
        /** Delete Client */
        delete: operations["delete_client_clients__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{client_id}/add-chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Chat */
        post: operations["add_chat_clients__client_id__add_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chats */
        get: operations["list_chats_chats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chats Stats */
        get: operations["get_chats_stats_chats_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chat */
        get: operations["get_chat_chats__id__get"];
        /** Update Chat */
        put: operations["update_chat_chats__id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_users__id__get"];
        put?: never;
        post?: never;
        /**
         * Delete User
         * @description Delete a user, all their messages, and clean up orphaned storage objects.
         *     Only accessible to super users.
         *
         *     This operation:
         *     1. Collects all storage object references from the user's messages
         *     2. Deletes all messages posted by this user
         *     3. Checks each storage object to see if it's still referenced by other messages
         *     4. Deletes storage objects that are no longer referenced (orphaned)
         *     5. Deletes the user record
         *
         *     Args:
         *         id: The user ID to delete
         *         account: The authenticated super user account
         *         database: The database connection
         *         storage: The storage connection for file operations
         *
         *     Returns:
         *         200 OK with deletion confirmation including counts of deleted messages and storage objects
         *         404 Not Found if the user doesn't exist
         */
        delete: operations["delete_user_users__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Metrics */
        get: operations["list_metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saved-searches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Saved Searches
         * @description List all saved searches
         */
        get: operations["list_saved_searches_saved_searches_get"];
        put?: never;
        /**
         * Save Search
         * @description Save a search
         */
        post: operations["save_search_saved_searches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saved-searches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Saved Search
         * @description Delete a client
         */
        delete: operations["delete_saved_search_saved_searches__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saved-searches/count-unread-messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Count Unread Messages */
        get: operations["count_unread_messages_saved_searches_count_unread_messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/{bucket_name}/{object_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get File */
        get: operations["get_file_storage__bucket_name___object_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountCreate */
        AccountCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean | null;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean | null;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean | null;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
        };
        /** AccountRead */
        AccountRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** AccountUpdate */
        AccountUpdate: {
            /** Password */
            password?: string | null;
            /** Email */
            email?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Is Superuser */
            is_superuser?: boolean | null;
            /** Is Verified */
            is_verified?: boolean | null;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
        };
        /** AddChatRequest */
        AddChatRequest: {
            /** Chat Id */
            chat_id: number;
        };
        /** AggregatedMetrics */
        AggregatedMetrics: {
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Time Delta */
            time_delta?: number | null;
            /** Sum */
            sum?: number | null;
            /** Diff */
            diff?: number | null;
            /** Data */
            data?: (number | null)[] | null;
        };
        /** BearerResponse */
        BearerResponse: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** Body_auth_jwt_login_auth_jwt_login_post */
        Body_auth_jwt_login_auth_jwt_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** Body_reset_forgot_password_auth_forgot_password_post */
        Body_reset_forgot_password_auth_forgot_password_post: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** Body_reset_reset_password_auth_reset_password_post */
        Body_reset_reset_password_auth_reset_password_post: {
            /** Token */
            token: string;
            /** Password */
            password: string;
        };
        /** Body_verify_request_token_auth_request_verify_token_post */
        Body_verify_request_token_auth_request_verify_token_post: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** Body_verify_verify_auth_verify_post */
        Body_verify_verify_auth_verify_post: {
            /** Token */
            token: string;
        };
        /**
         * ChatIn
         * @description The chat model with only those fields that can be modified by a client consuming
         *     the API (used in REST-API for POST/PUT/PATCH endpoints).
         */
        ChatIn: {
            /** Language */
            language?: string | null;
            /** Language Other */
            language_other?: string[] | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** ChatMetrics */
        ChatMetrics: {
            activity_last_day?: components["schemas"]["AggregatedMetrics"] | null;
            activity_total?: components["schemas"]["AggregatedMetrics"] | null;
            growth_last_day?: components["schemas"]["AggregatedMetrics"] | null;
            growth_total?: components["schemas"]["AggregatedMetrics"] | null;
        };
        /**
         * ChatOut
         * @description The complete chat model as it is returned by the REST-API.
         *     All fields except "id" are optional since the API allows to include/exclude fields.
         */
        ChatOut: {
            /** Language */
            language?: string | null;
            /** Language Other */
            language_other?: string[] | null;
            /** Tags */
            tags?: string[] | null;
            /** Id */
            id: number;
            type?: components["schemas"]["ChatType"] | null;
            /** Title */
            title?: string | null;
            /** Username */
            username?: string | null;
            verification_status?: components["schemas"]["VerificationStatus"] | null;
            /** Is Restricted */
            is_restricted?: boolean | null;
            /** Photo */
            photo?: {
                [key: string]: unknown;
            } | null;
            /** Description */
            description?: string | null;
            /** Invite Link */
            invite_link?: string | null;
            pinned_message?: components["schemas"]["MessageRef"] | null;
            /** Members */
            members?: components["schemas"]["UserRef"][] | null;
            /** Members Count */
            members_count?: number | null;
            metrics?: components["schemas"]["ChatMetrics"] | null;
            linked_chat?: components["schemas"]["ChatRef"] | null;
            /** Restrictions */
            restrictions?: {
                [key: string]: unknown;
            }[] | null;
            /** Permissions */
            permissions?: {
                [key: string]: unknown;
            } | null;
            /**
             * Added At
             * Format: date-time
             */
            added_at?: string;
            /** Updated At */
            updated_at?: string | null;
            /** History Updated At */
            history_updated_at?: string | null;
            /** Scraped By */
            scraped_by?: string | null;
            /** Similar Channels */
            similar_channels?: components["schemas"]["ChatRef"][] | null;
            classification_aggregated?: components["schemas"]["ClassificationAggregation"] | null;
            /** Highlight */
            highlight?: {
                [key: string]: string[];
            } | null;
            /** Score */
            score?: number | null;
        };
        /** ChatRef */
        ChatRef: {
            /** Id */
            id: number;
            /** Title */
            title?: string | null;
            /** Username */
            username?: string | null;
        };
        /**
         * ChatSortBy
         * @enum {string}
         */
        ChatSortBy: "title.keyword" | "members_count" | "updated_at" | "score";
        /** ChatSortOptions */
        ChatSortOptions: {
            sort_by: components["schemas"]["ChatSortBy"];
            order: components["schemas"]["OrderEnum"];
        };
        /** ChatStats */
        ChatStats: {
            /** Tags */
            tags?: components["schemas"]["StatsEntry"][] | null;
        };
        /**
         * ChatType
         * @enum {string}
         */
        ChatType: "GROUP" | "SUPERGROUP" | "CHANNEL";
        /** ClassificationAggregation */
        ClassificationAggregation: {
            /** Classified Success Count */
            classified_success_count?: number | null;
            /** Classified Error Count */
            classified_error_count?: number | null;
            /** Score Pos Avg */
            score_pos_avg?: number | null;
        };
        /** ClientCreate */
        ClientCreate: {
            /** Title */
            title: string;
            /** Phone Number */
            phone_number: string;
            /** Api Id */
            api_id: number;
            /** Api Hash */
            api_hash: string;
            /** Id */
            id: string;
            /** Session Hash */
            session_hash?: string | null;
            /** User Id */
            user_id?: number | null;
            /** Chats */
            chats?: components["schemas"]["ChatRef"][] | null;
            /** Chats To Join */
            chats_to_join?: string[] | null;
            /**
             * Is Active
             * @default false
             */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            auth: components["schemas"]["SentCode"];
        };
        /**
         * ClientIn
         * @description The client model with Telegram auth infos and only those fields that can be
         *     modified by a client consuming the API (used in REST-API for
         *     POST/PUT/PATCH endpoints).
         */
        ClientIn: {
            /** Title */
            title: string;
            /** Phone Number */
            phone_number: string;
            /** Api Id */
            api_id: number;
            /** Api Hash */
            api_hash: string;
        };
        /**
         * ClientOut
         * @description The complete client model as it is returned by the REST-API.
         */
        ClientOut: {
            /** Title */
            title: string;
            /** Phone Number */
            phone_number: string;
            /** Api Id */
            api_id: number;
            /** Api Hash */
            api_hash: string;
            /** Id */
            id: string;
            /** Session Hash */
            session_hash?: string | null;
            /** User Id */
            user_id?: number | null;
            /** Chats */
            chats?: components["schemas"]["ChatRef"][] | null;
            /** Chats To Join */
            chats_to_join?: string[] | null;
            /**
             * Is Active
             * @default false
             */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /**
         * ClientSortBy
         * @enum {string}
         */
        ClientSortBy: "title" | "created_at" | "updated_at";
        /** ClientSortOptions */
        ClientSortOptions: {
            sort_by: components["schemas"]["ClientSortBy"];
            order: components["schemas"]["OrderEnum"];
        };
        /** ClientUpdate */
        ClientUpdate: {
            /** Title */
            title?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ClientVerifyPassword */
        ClientVerifyPassword: {
            /** Password */
            password: string;
        };
        /** ClientVerifyPhoneCode */
        ClientVerifyPhoneCode: {
            /** Phone Code Hash */
            phone_code_hash: string;
            /** Phone Code */
            phone_code: string;
        };
        /** ErrorModel */
        ErrorModel: {
            /** Detail */
            detail: string | {
                [key: string]: string;
            };
        };
        /** GlobalMetrics */
        GlobalMetrics: {
            /** Users Count */
            users_count?: number | null;
            /** Chats Count */
            chats_count?: number | null;
            /** Messages Count */
            messages_count?: number | null;
            /** Photos Count */
            photos_count?: number | null;
            /** Videos Count */
            videos_count?: number | null;
            /** Voices Count */
            voices_count?: number | null;
            growth_total?: components["schemas"]["AggregatedMetrics"] | null;
            activity_total?: components["schemas"]["AggregatedMetrics"] | null;
            classification_total?: components["schemas"]["ClassificationAggregation"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ListMessagesParams */
        ListMessagesParams: {
            /** Saved Search Id */
            saved_search_id?: string | null;
            /** From User Ids */
            from_user_ids?: number[] | null;
            /** Chat Ids */
            chat_ids?: number[] | null;
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
            /** Is Empty */
            is_empty?: boolean | null;
            attachment_type?: components["schemas"]["MessageMediaType"] | null;
            /** Tags */
            tags?: string[] | null;
            /** Chat Tags */
            chat_tags?: string[] | null;
            /** Search Query */
            search_query?: string | null;
            sort_by?: components["schemas"]["MessageSortBy"] | null;
            order?: components["schemas"]["OrderEnum"] | null;
            /** Include */
            include?: string[] | null;
            /** Exclude */
            exclude?: string[] | null;
            search_type: components["schemas"]["MessageSearchType"];
        };
        /** MessageAttachment */
        MessageAttachment: {
            type: components["schemas"]["MessageMediaType"];
            /** Group Id */
            group_id?: number | null;
            /** Raw */
            raw?: {
                [key: string]: unknown;
            } | null;
            /** Transcription */
            transcription?: string | null;
            /** Transcription Language */
            transcription_language?: string | null;
            /** Transcription Language Probability */
            transcription_language_probability?: number | null;
            transcription_status?: components["schemas"]["TranscriptionStatus"] | null;
            /** Storage Refs */
            storage_refs?: components["schemas"]["MessageAttachmentStorageRef"][] | null;
        };
        /** MessageAttachmentStorageRef */
        MessageAttachmentStorageRef: {
            /** Bucket */
            bucket: string;
            /** Object */
            object: string;
        };
        /** MessageEntity */
        MessageEntity: {
            type: components["schemas"]["MessageEntityType"];
            /** Offset */
            offset: number;
            /** Length */
            length: number;
            /** Url */
            url?: string | null;
            user?: components["schemas"]["UserRef"] | null;
            /** Language */
            language?: string | null;
            /** Custom Emoji Id */
            custom_emoji_id?: number | null;
        };
        /**
         * MessageEntityType
         * @enum {string}
         */
        MessageEntityType: "mention" | "hashtag" | "cashtag" | "bot_command" | "url" | "email" | "phone_number" | "bold" | "italic" | "underline" | "strikethrough" | "spoiler" | "code" | "pre" | "blockquote" | "text_link" | "text_mention" | "bank_card" | "custom_emoji" | "unknown";
        /** MessageForward */
        MessageForward: {
            from_user?: components["schemas"]["UserRef"] | null;
            /** Sender Name */
            sender_name?: string | null;
            from_chat?: components["schemas"]["ChatRef"] | null;
            /** From Message Id */
            from_message_id?: number | null;
            /** Signature */
            signature?: string | null;
            /** Date */
            date?: string | null;
        };
        /**
         * MessageIn
         * @description The message model with only those fields that can be modified by a client consuming
         *     the API (used in REST-API for POST/PUT/PATCH endpoints).
         *
         *     Adapted from Pyrograms message model:
         *     https://docs.pyrogram.org/api/types/Message#pyrogram.types.Message
         */
        MessageIn: {
            /** Language */
            language?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /**
         * MessageMediaType
         * @description Message media type enumeration used in :obj:`~pyrogram.types.Message`.
         * @enum {string}
         */
        MessageMediaType: "unsupported" | "audio" | "document" | "photo" | "sticker" | "video" | "animation" | "voice" | "video_note" | "contact" | "location" | "venue" | "poll" | "web_page" | "dice" | "game" | "giveaway" | "giveaway_winners" | "story" | "invoice" | "paid_media" | "checklist";
        /**
         * MessageOut
         * @description The complete message model as it is returned by the REST-API.
         *     All fields except "id" are optional since the API allows to include/exclude fields.
         */
        MessageOut: {
            /** Language */
            language?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Id */
            id: string;
            /** Id In Chat */
            id_in_chat?: number | null;
            from_user?: components["schemas"]["UserRef"] | null;
            chat?: components["schemas"]["ChatRef"] | null;
            sender_chat?: components["schemas"]["ChatRef"] | null;
            /** Date */
            date?: string | null;
            forward?: components["schemas"]["MessageForward"] | null;
            reply_to_message?: components["schemas"]["MessageRef"] | null;
            /** Mentioned */
            mentioned?: boolean | null;
            /** Is Empty */
            is_empty?: boolean | null;
            attachment?: components["schemas"]["MessageAttachment"] | null;
            /** Edit Date */
            edit_date?: string | null;
            /** Author Signature */
            author_signature?: string | null;
            /** Text */
            text?: string | null;
            /** Entities */
            entities?: components["schemas"]["MessageEntity"][] | null;
            /** Caption */
            caption?: string | null;
            /** Caption Entities */
            caption_entities?: components["schemas"]["MessageEntity"][] | null;
            /** Views */
            views?: number | null;
            /** Is Outgoing */
            is_outgoing?: boolean | null;
            service_info?: components["schemas"]["MessageServiceInfo"] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /** Scraped By */
            scraped_by?: string | null;
            /** Deleted */
            deleted?: string | null;
            scraping_mode?: components["schemas"]["ScrapingMode"] | null;
            /** Extracted Urls */
            extracted_urls?: {
                [key: string]: unknown;
            }[] | null;
            /** Extracted Hashtags */
            extracted_hashtags?: string[] | null;
            /** Highlight */
            highlight?: {
                [key: string]: string[];
            } | null;
            /** Score */
            score?: number | null;
            /** Classification Score Pos */
            classification_score_pos?: number | null;
            /** Semantic Score */
            semantic_score?: number | null;
        };
        /** MessageRef */
        MessageRef: {
            /** Id */
            id: string;
            /** Text */
            text?: string | null;
            /** Caption */
            caption?: string | null;
            /** Has Attachment */
            has_attachment?: boolean | null;
            user?: components["schemas"]["UserRef"] | null;
        };
        /**
         * MessageSearchType
         * @enum {string}
         */
        MessageSearchType: "exact" | "flexible" | "fuzzy" | "semantic_text" | "semantic_image";
        /** MessageServiceInfo */
        MessageServiceInfo: {
            service_type?: components["schemas"]["MessageServiceType"] | null;
            /** New Chat Members */
            new_chat_members?: components["schemas"]["UserRef"][] | null;
            left_chat_member?: components["schemas"]["UserRef"] | null;
            /** New Chat Title */
            new_chat_title?: string | null;
            /** New Chat Photo */
            new_chat_photo?: {
                [key: string]: unknown;
            } | null;
            /** Delete Chat Photo */
            delete_chat_photo?: boolean | null;
            /** Group Chat Created */
            group_chat_created?: boolean | null;
            /** Supergroup Chat Created */
            supergroup_chat_created?: boolean | null;
            /** Channel Chat Created */
            channel_chat_created?: boolean | null;
            /** Migrate To Chat Id */
            migrate_to_chat_id?: number | null;
            /** Migrate From Chat Id */
            migrate_from_chat_id?: number | null;
            /** Pinned Message Id */
            pinned_message_id?: number | null;
            /** History Cleared */
            history_cleared?: boolean | null;
            /** Set Message Auto Delete Time */
            set_message_auto_delete_time?: number | null;
            /** Screenshot Taken */
            screenshot_taken?: boolean | null;
            /** Proximity Alert Triggered */
            proximity_alert_triggered?: boolean | null;
        };
        /**
         * MessageServiceType
         * @description Message service type enumeration compatible with Pydantic.
         * @enum {string}
         */
        MessageServiceType: "UNSUPPORTED" | "CUSTOM_ACTION" | "NEW_CHAT_MEMBERS" | "LEFT_CHAT_MEMBER" | "NEW_CHAT_TITLE" | "NEW_CHAT_PHOTO" | "DELETE_CHAT_PHOTO" | "FORUM_TOPIC_CREATED" | "FORUM_TOPIC_CLOSED" | "FORUM_TOPIC_REOPENED" | "FORUM_TOPIC_EDITED" | "GENERAL_FORUM_TOPIC_HIDDEN" | "GENERAL_FORUM_TOPIC_UNHIDDEN" | "GROUP_CHAT_CREATED" | "CHANNEL_CHAT_CREATED" | "SUPERGROUP_CHAT_CREATED" | "MIGRATE_TO_CHAT_ID" | "MIGRATE_FROM_CHAT_ID" | "PINNED_MESSAGE" | "GAME_HIGH_SCORE" | "GIVEAWAY_CREATED" | "GIVEAWAY_COMPLETED" | "GIFT_CODE" | "GIFTED_PREMIUM" | "GIFTED_STARS" | "GIFTED_TON" | "VIDEO_CHAT_STARTED" | "VIDEO_CHAT_ENDED" | "VIDEO_CHAT_SCHEDULED" | "VIDEO_CHAT_MEMBERS_INVITED" | "PHONE_CALL_STARTED" | "PHONE_CALL_ENDED" | "WEB_APP_DATA" | "USERS_SHARED" | "CHAT_SHARED" | "SUCCESSFUL_PAYMENT" | "REFUNDED_PAYMENT" | "SUGGESTED_POST_APPROVAL_FAILED" | "SUGGESTED_POST_APPROVED" | "SUGGESTED_POST_DECLINED" | "SUGGESTED_POST_PAID" | "SUGGESTED_POST_REFUNDED" | "SET_MESSAGE_AUTO_DELETE_TIME" | "CHAT_BOOST" | "GIFT" | "CONNECTED_WEBSITE" | "WRITE_ACCESS_ALLOWED" | "SCREENSHOT_TAKEN" | "CONTACT_REGISTERED" | "PROXIMITY_ALERT_TRIGGERED" | "HISTORY_CLEARED" | "SUGGEST_PROFILE_PHOTO" | "SUGGEST_BIRTHDAY" | "CHAT_SET_BACKGROUND" | "CHAT_SET_THEME" | "GIVEAWAY_PRIZE_STARS" | "PAID_MESSAGES_REFUNDED" | "PAID_MESSAGES_PRICE_CHANGED" | "DIRECT_MESSAGE_PRICE_CHANGED" | "CHECKLIST_TASKS_DONE" | "CHECKLIST_TASKS_ADDED";
        /**
         * MessageSortBy
         * @enum {string}
         */
        MessageSortBy: "date" | "score" | "classification.score_pos";
        /** MessageSortOptions */
        MessageSortOptions: {
            sort_by: components["schemas"]["MessageSortBy"];
            order: components["schemas"]["OrderEnum"];
        };
        /** MessageStats */
        MessageStats: {
            /** Extracted Hashtags */
            extracted_hashtags?: components["schemas"]["StatsEntry"][] | null;
            /** Extracted Domains */
            extracted_domains?: components["schemas"]["StatsEntry"][] | null;
            /** Attachment Types */
            attachment_types?: components["schemas"]["StatsEntry"][] | null;
            /** Tags */
            tags?: components["schemas"]["StatsEntry"][] | null;
        };
        /** MessagesCount */
        MessagesCount: {
            /** Count Total */
            count_total: number;
            /** Count Unread */
            count_unread: number;
        };
        /**
         * NextCodeType
         * @description Copy of Pyrograms next code type enumeration used in :obj:`~pyrogram.types.SentCode`.
         * @enum {string}
         */
        NextCodeType: "CALL" | "FLASH_CALL" | "MISSED_CALL" | "SMS" | "FRAGMENT_SMS";
        /**
         * OrderEnum
         * @enum {string}
         */
        OrderEnum: "asc" | "desc";
        /** PaginatedAccounts */
        PaginatedAccounts: {
            /** Data */
            data: components["schemas"]["AccountRead"][];
            pagination: components["schemas"]["PaginatedResponseInfo"];
            sort: components["schemas"]["SortOptions"] | null;
            /** Count Total */
            count_total: number | null;
        };
        /** PaginatedChats */
        PaginatedChats: {
            /** Data */
            data: components["schemas"]["ChatOut"][];
            pagination: components["schemas"]["PaginatedResponseInfo"];
            sort: components["schemas"]["ChatSortOptions"];
            /** Count Total */
            count_total: number | null;
        };
        /** PaginatedClients */
        PaginatedClients: {
            /** Data */
            data: components["schemas"]["ClientOut"][];
            pagination: components["schemas"]["PaginatedResponseInfo"];
            sort: components["schemas"]["ClientSortOptions"];
            /** Count Total */
            count_total: number | null;
        };
        /** PaginatedMessages */
        PaginatedMessages: {
            /** Data */
            data: components["schemas"]["MessageOut"][];
            pagination: components["schemas"]["PaginatedResponseInfo"];
            sort: components["schemas"]["MessageSortOptions"];
            /** Count Total */
            count_total: number | null;
        };
        /** PaginatedResponseInfo */
        PaginatedResponseInfo: {
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Max Limit */
            max_limit: number;
        };
        /** PaginatedUsers */
        PaginatedUsers: {
            /** Data */
            data: components["schemas"]["UserOut"][];
            pagination: components["schemas"]["PaginatedResponseInfo"];
            sort: components["schemas"]["UserSortOptions"];
            /** Count Total */
            count_total: number | null;
        };
        /** SavedSearchIn */
        SavedSearchIn: {
            /** Name */
            name: string;
            params: components["schemas"]["ListMessagesParams"];
        };
        /** SavedSearchOut */
        SavedSearchOut: {
            /** Name */
            name: string;
            params: components["schemas"]["ListMessagesParams"];
            /** Id */
            id: string;
            /**
             * Last Visited
             * Format: date-time
             */
            last_visited?: string;
        };
        /**
         * ScrapingMode
         * @enum {string}
         */
        ScrapingMode: "history" | "live";
        /** SentCode */
        SentCode: {
            type: components["schemas"]["SentCodeType"];
            /** Phone Code Hash */
            phone_code_hash: string;
            next_type?: components["schemas"]["NextCodeType"] | null;
            /** Timeout */
            timeout?: number | null;
        };
        /**
         * SentCodeType
         * @description Copy of Pyrograms sent code type enumeration used in :obj:`~pyrogram.types.SentCode`.
         * @enum {string}
         */
        SentCodeType: "APP" | "CALL" | "FLASH_CALL" | "MISSED_CALL" | "SMS" | "FRAGMENT_SMS" | "EMAIL_CODE";
        /** SortOptions */
        SortOptions: {
            /** Sort By */
            sort_by: components["schemas"]["ChatSortBy"] | components["schemas"]["MessageSortBy"] | components["schemas"]["UserSortBy"] | components["schemas"]["ClientSortBy"];
            order: components["schemas"]["OrderEnum"];
        };
        /** StatsEntry */
        StatsEntry: {
            /** Value */
            value: string;
            /** Count */
            count: number;
        };
        /**
         * TranscriptionStatus
         * @enum {string}
         */
        TranscriptionStatus: "PENDING" | "SUCCESS" | "FAILURE";
        /** UserMetrics */
        UserMetrics: {
            activity_last_day?: components["schemas"]["AggregatedMetrics"] | null;
            activity_total?: components["schemas"]["AggregatedMetrics"] | null;
        };
        /**
         * UserOut
         * @description The complete user model as it is returned by the REST-API.
         *     All fields except "id" are optional since the API allows to include/exclude fields.
         */
        UserOut: {
            /** Id */
            id: number;
            /** Username */
            username?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Is Self */
            is_self?: boolean | null;
            /** Is Contact */
            is_contact?: boolean | null;
            /** Is Mutual Contact */
            is_mutual_contact?: boolean | null;
            /** Is Deleted */
            is_deleted?: boolean | null;
            /** Is Bot */
            is_bot?: boolean | null;
            verification_status?: components["schemas"]["VerificationStatus"] | null;
            /** Is Restricted */
            is_restricted?: boolean | null;
            /** Is Support */
            is_support?: boolean | null;
            metrics?: components["schemas"]["UserMetrics"] | null;
            status?: components["schemas"]["UserStatus"] | null;
            /** Last Online Date */
            last_online_date?: string | null;
            /** Next Offline Date */
            next_offline_date?: string | null;
            /** Language Code */
            language_code?: string | null;
            /** Dc Id */
            dc_id?: number | null;
            /** Phone Number */
            phone_number?: string | null;
            /** Photo */
            photo?: {
                [key: string]: unknown;
            } | null;
            /** Restrictions */
            restrictions?: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /** Scraped By */
            scraped_by?: string | null;
            /** In Chats */
            in_chats?: components["schemas"]["ChatRef"][] | null;
            /** Highlight */
            highlight?: {
                [key: string]: string[];
            } | null;
            /** Score */
            score?: number | null;
        };
        /** UserRef */
        UserRef: {
            /** Id */
            id: number;
            /** Username */
            username?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
        };
        /**
         * UserSortBy
         * @enum {string}
         */
        UserSortBy: "score" | "username.keyword" | "updated_at";
        /** UserSortOptions */
        UserSortOptions: {
            sort_by: components["schemas"]["UserSortBy"];
            order: components["schemas"]["OrderEnum"];
        };
        /**
         * UserStatus
         * @description Copy of Pyrograms user status enumeration used in :obj:`~pyrogram.types.User`.
         * @enum {string}
         */
        UserStatus: "ONLINE" | "OFFLINE" | "RECENTLY" | "LAST_WEEK" | "LAST_MONTH" | "LONG_AGO";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerificationStatus
         * @description Contains information about verification status of a chat or a user.
         */
        VerificationStatus: {
            /** Is Verified */
            is_verified?: boolean | null;
            /** Is Scam */
            is_scam?: boolean | null;
            /** Is Fake */
            is_fake?: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    auth_jwt_login_auth_jwt_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_auth_jwt_login_auth_jwt_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiOTIyMWZmYzktNjQwZi00MzcyLTg2ZDMtY2U2NDJjYmE1NjAzIiwiYXVkIjoiZmFzdGFwaS11c2VyczphdXRoIiwiZXhwIjoxNTcxNTA0MTkzfQ.M10bjOe45I5Ncu_uXvOmVV8QxnL-nZfcH96U90JaocI",
                     *       "token_type": "bearer"
                     *     } */
                    "application/json": components["schemas"]["BearerResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_jwt_logout_auth_jwt_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_jwt_auth_jwt_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_forgot_password_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_reset_forgot_password_auth_forgot_password_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_reset_password_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_reset_reset_password_auth_reset_password_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_request_token_auth_request_verify_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_verify_request_token_auth_request_verify_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_verify_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_verify_verify_auth_verify_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_current_user_accounts_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_patch_current_user_accounts_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_user_accounts__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_delete_user_accounts__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_patch_user_accounts__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_accounts_accounts_get: {
        parameters: {
            query?: {
                include?: string[] | null;
                exclude?: string[] | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAccounts"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_messages_get: {
        parameters: {
            query?: {
                chat_tags?: string[] | null;
                search_type?: components["schemas"]["MessageSearchType"];
                search_query?: string | null;
                saved_search_id?: string | null;
                from_user_ids?: number[] | null;
                chat_ids?: number[] | null;
                date_from?: string | null;
                date_to?: string | null;
                is_empty?: boolean | null;
                attachment_type?: components["schemas"]["MessageMediaType"] | null;
                tags?: string[] | null;
                sort_by?: components["schemas"]["MessageSortBy"] | null;
                order?: components["schemas"]["OrderEnum"] | null;
                include?: string[] | null;
                exclude?: string[] | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List matching messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMessages"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_messages_stats_messages_stats_get: {
        parameters: {
            query?: {
                from_user_ids?: number[] | null;
                chat_ids?: number[] | null;
                date_from?: string | null;
                date_to?: string | null;
                is_empty?: boolean | null;
                attachment_type?: components["schemas"]["MessageMediaType"] | null;
                tags?: string[] | null;
                search_query?: string | null;
                fuzzy?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return message statistics (top hashtags, domains, etc.) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    show_message_messages__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get a single message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_message_messages__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageIn"];
            };
        };
        responses: {
            /** @description Update a message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clients_clients_get: {
        parameters: {
            query?: {
                is_active?: boolean | null;
                phone_number?: string | null;
                user_id?: number | null;
                chat_ids?: number[] | null;
                sort_by?: components["schemas"]["ClientSortBy"] | null;
                order?: components["schemas"]["OrderEnum"] | null;
                include?: string[] | null;
                exclude?: string[] | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all clients */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedClients"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_clients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientIn"];
            };
        };
        responses: {
            /** @description Create a new client */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientCreate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_phone_code_clients__id__verify_phone_code_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientVerifyPhoneCode"];
            };
        };
        responses: {
            /** @description Verify phone code for client authentication */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_password_clients__id__verify_password_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientVerifyPassword"];
            };
        };
        responses: {
            /** @description Verify 2FA/cloud password for client authentication */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_clients__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get a single client */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_client_clients__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientUpdate"];
            };
        };
        responses: {
            /** @description Update a client */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_client_clients__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete a client */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_chat_clients__client_id__add_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddChatRequest"];
            };
        };
        responses: {
            /** @description Add a chat to the client's list of chats to join */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chats_chats_get: {
        parameters: {
            query?: {
                aggregations?: boolean | null;
                type?: components["schemas"]["ChatType"] | null;
                is_verified?: boolean | null;
                is_restricted?: boolean | null;
                is_scam?: boolean | null;
                is_fake?: boolean | null;
                tags?: string[] | null;
                search_query?: string | null;
                sort_by?: components["schemas"]["ChatSortBy"] | null;
                order?: components["schemas"]["OrderEnum"] | null;
                include?: string[] | null;
                exclude?: string[] | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List matching chats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedChats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chats_stats_chats_stats_get: {
        parameters: {
            query?: {
                type?: components["schemas"]["ChatType"] | null;
                is_verified?: boolean | null;
                is_restricted?: boolean | null;
                is_scam?: boolean | null;
                is_fake?: boolean | null;
                tags?: string[] | null;
                search_query?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return chat statistics (top tags) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_chats__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get a single chat */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_chat_chats__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatIn"];
            };
        };
        responses: {
            /** @description Update a chat */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_users_get: {
        parameters: {
            query?: {
                is_deleted?: boolean | null;
                is_bot?: boolean | null;
                is_verified?: boolean | null;
                is_restricted?: boolean | null;
                is_scam?: boolean | null;
                is_fake?: boolean | null;
                is_support?: boolean | null;
                phone_number?: string | null;
                search_query?: string | null;
                sort_by?: components["schemas"]["UserSortBy"] | null;
                order?: components["schemas"]["OrderEnum"] | null;
                include?: string[] | null;
                exclude?: string[] | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List matching users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUsers"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_users__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get a single user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_users__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete a user and their messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalMetrics"];
                };
            };
        };
    };
    list_saved_searches_saved_searches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of all saved searches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedSearchOut"][];
                };
            };
        };
    };
    save_search_saved_searches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedSearchIn"];
            };
        };
        responses: {
            /** @description The saved search */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedSearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_saved_search_saved_searches__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    count_unread_messages_saved_searches_count_unread_messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Count all unread messages of all saved searches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["MessagesCount"];
                    };
                };
            };
        };
    };
    list_tags_tags_get: {
        parameters: {
            query?: {
                from_user_ids?: number[] | null;
                chat_ids?: number[] | null;
                date_from?: string | null;
                date_to?: string | null;
                is_empty?: boolean | null;
                attachment_type?: components["schemas"]["MessageMediaType"] | null;
                tags?: string[] | null;
                search_query?: string | null;
                fuzzy?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_storage__bucket_name___object_name__get: {
        parameters: {
            query?: {
                attachment?: boolean;
            };
            header?: never;
            path: {
                bucket_name: string;
                object_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requested file from storage. Can be of any media type. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": unknown;
                };
            };
            /** @description Any other error why the file could not be fetched. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The bucket or file was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
